# Generated by Django 3.1.6 on 2021-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000)),
                ('uid', models.IntegerField(max_length=11)),
                ('create_time', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Browse',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(max_length=11)),
                ('bid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(max_length=11)),
                ('bid', models.IntegerField(max_length=11)),
                ('content', models.TextField(max_length=1000)),
                ('create_time', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(max_length=11)),
                ('fid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('introduce', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
